### ISSUE TITLE
add other labels 

### ISSUE THREAD

**Issue by reginawang3495** [uclaacm/teach-la-ts-react-starter#71]
ideas could include p0, p1, ..., or blocked!

**Comment by doubleiis02** [comment]
### PR type
- **feature**: new feature or request
- **major-update**: a major update
- **minor-update**: a minor update
- **bug**: something isn't working
- **cleanup**: clean up some code
- **tracking**: issues that track a subject or multiple issues
- **dependencies**: pull requests that update a dependency file
- **documentation**: improvements or additions to documentation
- **design**: this needs lofi/hifi design
- **content**: this adds learning lab content
- **question**: further information is requested

### effort

- **effort/large**: large work item - a week or more
- **effort/medium**: medium work item - around a week
- **effort/small**: small work item - around 1 to 2 nights
- **effort/tiny**: tiny work item - around 0 to 2 hours

### priority

- **p0**: needs to be done ASAP
- **p1**: needs to be done relatively soon
- **p2**: could wait a while
- **p3**: we'll do this at some point
- **blocked**: this issue is waiting on something else

### difficulty

- **good first issue**: good for newcomers
- **need guidance**: extra attention is needed
